server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true		# group ??
  swagger-ui:
    doc-expansion: none